name: numerical_methods_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Serial ..
    - name: make
      run: make
    - name: test
      run: ./build/bin/scalarIVP
