name: numerical_methods_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  serial-no_eigen:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: configure
      working-directory: ${{github.workspace}}
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Serial ../
    - name: make
      working-directory: ${{github.workspace}}/build
      run: make
    - name: scalarIVP
      working-directory: ${{github.workspace}}/build
      run: ./bin/scalarIVP
    - name: vectorIVP
      working-directory: ${{github.workspace}}/build
      run: ./bin/vectorIVP -N 10
    - name: Problem_6_2
      working-directory: ${{github.workspace}}/build
      run: ./bin/Problem_6_2 -N 10

  serial-yes_eigen:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: configure
      working-directory: ${{github.workspace}}
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Serial -DUSE_EIGEN=YES ../
    - name: make
      working-directory: ${{github.workspace}}/build
      run: make
    - name: scalarIVP
      working-directory: ${{github.workspace}}/build
      run: ./bin/scalarIVP
    - name: vectorIVP
      working-directory: ${{github.workspace}}/build
      run: ./bin/vectorIVP -N 10
    - name: Problem_6_2
      working-directory: ${{github.workspace}}/build
      run: ./bin/Problem_6_2 -N 10

  GPU:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: configure
      working-directory: ${{github.workspace}}
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=GPU ../
    - name: make
      working-directory: ${{github.workspace}}/build
      run: make
    - name: test
      working-directory: ${{github.workspace}}/build
      run: ./bin/CUmatFunTest

        #HybridCPU:

        #runs-on: self-hosted

        #steps:
        #- uses: actions/checkout@v3
        #- name: configure
        #working-directory: ${{github.workspace}}
        #run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=HybridCPU ../
        #- name: make
        #working-directory: ${{github.workspace}}/build
        #run: make
        #- name: test
        #working-directory: ${{github.workspace}}/build
        #run: mpirun -n 1 ./bin/scalarIVP
