name: numerical_methods_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: configure
      working-directory: ${{github.workspace}}/build
      run: ls && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Serial ../..
    - name: make
      working-directory: ${{github.workspace}}/build
      run: make
    - name: test
      working-directory: ${{github.workspace}}/build
      run: ./bin/scalarIVP
